### ISSUE TITLE
cannot create blob store with PKCS8 private key

### ISSUE THREAD

**Issue by pmarjou22** [Aiven-Open/encrypted-repository-opensearch#72]
Hello,

I try to build the plugin for opensearch 2.9.0. 

1. At first I have an integration test error at build time

```
org.opensearch.repository.encrypted.EncryptedRepositoryPluginIT > testCreateRepository FAILED
    RepositoryVerificationException[[enc-repo] path  is not accessible on cluster-manager node]; nested: RepositoryException[[enc-repo] cannot create blob store]; nested: ExecutionException[java.security.AccessControlException: access denied ("java.security.SecurityPermission" "removeProviderProperty.BC")]; nested: AccessControlException[access denied ("java.security.SecurityPermission" "removeProviderProperty.BC")];
        at __randomizedtesting.SeedInfo.seed([7BE41235BCABEC69:76C73B12B1AC0D47]:0)
        at app//org.opensearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:1861)
        at app//org.opensearch.repositories.RepositoriesService$3.doRun(RepositoriesService.java:329)
        at app//org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908)
        at app//org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
        at java.base@11.0.18/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base@11.0.18/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base@11.0.18/java.lang.Thread.run(Thread.java:829)
```

2. If I use the generated plugin (ignoring integration test error) I'm facing a fatal error at Opensearch start

```
org.opensearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to load plugin class [org.opensearch.repository.encrypted.EncryptedRepositoryPlugin]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:184) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-2.9.0.jar:2.9.0]
	at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-2.9.0.jar:2.9.0]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103) ~[opensearch-2.9.0.jar:2.9.0]
Caused by: java.lang.IllegalStateException: failed to load plugin class [org.opensearch.repository.encrypted.EncryptedRepositoryPlugin]
	at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:791) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:731) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:533) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:195) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.node.Node.<init>(Node.java:462) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.node.Node.<init>(Node.java:389) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) ~[opensearch-2.9.0.jar:2.9.0]
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:784) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:731) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:533) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:195) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.node.Node.<init>(Node.java:462) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.node.Node.<init>(Node.java:389) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) ~[opensearch-2.9.0.jar:2.9.0]
	... 6 more
Caused by: org.opensearch.common.settings.SettingsException: Couldn't generate RSA key pair
	at org.opensearch.repository.encrypted.security.RsaKeysReader.readRsaKeyPair(RsaKeysReader.java:43) ~[?:?]
	at org.opensearch.repository.encrypted.EncryptedRepositorySettings.createKeyPair(EncryptedRepositorySettings.java:153) ~[?:?]
	at org.opensearch.repository.encrypted.EncryptedRepositorySettings.load(EncryptedRepositorySettings.java:139) ~[?:?]
	at org.opensearch.repository.encrypted.EncryptedRepositoryPlugin.lambda$loadSettings$1(EncryptedRepositoryPlugin.java:63) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
	at org.opensearch.repository.encrypted.Permissions.doPrivileged(Permissions.java:21) ~[?:?]
	at org.opensearch.repository.encrypted.EncryptedRepositoryPlugin.loadSettings(EncryptedRepositoryPlugin.java:63) ~[?:?]
	at org.opensearch.repository.encrypted.EncryptedRepositoryPlugin.<init>(EncryptedRepositoryPlugin.java:58) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:784) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:731) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:533) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:195) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.node.Node.<init>(Node.java:462) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.node.Node.<init>(Node.java:389) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) ~[opensearch-2.9.0.jar:2.9.0]
	... 6 more
Caused by: java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: IOException : algid parse error, not a sequence
	at sun.security.rsa.RSAKeyFactory.engineGeneratePrivate(RSAKeyFactory.java:253) ~[?:?]
	at java.security.KeyFactory.generatePrivate(KeyFactory.java:389) ~[?:?]
	at org.opensearch.repository.encrypted.security.RsaKeysReader.readPrivateKey(RsaKeysReader.java:65) ~[?:?]
	at org.opensearch.repository.encrypted.security.RsaKeysReader.readRsaKeyPair(RsaKeysReader.java:40) ~[?:?]
	at org.opensearch.repository.encrypted.EncryptedRepositorySettings.createKeyPair(EncryptedRepositorySettings.java:153) ~[?:?]
	at org.opensearch.repository.encrypted.EncryptedRepositorySettings.load(EncryptedRepositorySettings.java:139) ~[?:?]
	at org.opensearch.repository.encrypted.EncryptedRepositoryPlugin.lambda$loadSettings$1(EncryptedRepositoryPlugin.java:63) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
	at org.opensearch.repository.encrypted.Permissions.doPrivileged(Permissions.java:21) ~[?:?]
	at org.opensearch.repository.encrypted.EncryptedRepositoryPlugin.loadSettings(EncryptedRepositoryPlugin.java:63) ~[?:?]
	at org.opensearch.repository.encrypted.EncryptedRepositoryPlugin.<init>(EncryptedRepositoryPlugin.java:58) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:784) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:731) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:533) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:195) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.node.Node.<init>(Node.java:462) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.node.Node.<init>(Node.java:389) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) ~[opensearch-2.9.0.jar:2.9.0]
	... 6 more
```
	
	

3. I bypass this problem by converting convert PKCS1 private key to a  PKCS8 private key

4. Opensearch start now but : I'm now facing an error "cannot create blob store" due to execution_exception: java.security.AccessControlException: access denied (\"java.security.SecurityPermission\" \"getProperty.org.bouncycastle.rsa.max_size\")

	
```
org.opensearch.transport.RemoteTransportException: [ES_MASTERHA_0][:9300][cluster:admin/snapshot/get]
Caused by: org.opensearch.repositories.RepositoryException: [s3-repositoryencr] cannot create blob store
	at org.opensearch.repositories.blobstore.BlobStoreRepository.blobStore(BlobStoreRepository.java:752) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.repositories.blobstore.BlobStoreRepository.blobContainer(BlobStoreRepository.java:725) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.repositories.blobstore.BlobStoreRepository.listBlobsToGetLatestIndexId(BlobStoreRepository.java:2557) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.repositories.blobstore.BlobStoreRepository.latestIndexBlobId(BlobStoreRepository.java:2539) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.repositories.blobstore.BlobStoreRepository.doGetRepositoryData(BlobStoreRepository.java:1919) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:88) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.9.0.jar:2.9.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.opensearch.common.io.stream.NotSerializableExceptionWrapper: execution_exception: java.security.AccessControlException: access denied ("java.security.SecurityPermission" "getProperty.org.bouncycastle.rsa.max_size")
	at org.opensearch.common.cache.Cache.computeIfAbsent(Cache.java:464) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.repository.encrypted.EncryptedRepository.createBlobStore(EncryptedRepository.java:138) ~[?:?]
	at org.opensearch.repositories.blobstore.BlobStoreRepository.blobStore(BlobStoreRepository.java:748) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.repositories.blobstore.BlobStoreRepository.blobContainer(BlobStoreRepository.java:725) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.repositories.blobstore.BlobStoreRepository.listBlobsToGetLatestIndexId(BlobStoreRepository.java:2557) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.repositories.blobstore.BlobStoreRepository.latestIndexBlobId(BlobStoreRepository.java:2539) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.repositories.blobstore.BlobStoreRepository.doGetRepositoryData(BlobStoreRepository.java:1919) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:88) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.9.0.jar:2.9.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

5.  Do you have any idea of what I could be doing wrong ?

Thanks for your help !

**Comment by willyborankin** [comment]
Hi, @pmarjou22 thank you for the feedback. I haven't prepared 2.9.0 version.

**Comment by willyborankin** [comment]
and It needs addition permissions. "java.security.SecurityPermission" "getProperty.org.bouncycastle.rsa.max_size" will fix it

**Comment by willyborankin** [comment]
2.9.0.0 - released

**Comment by pmarjou22** [comment]
Hello @willyborankin,

The 2.9.0.0 still have the error access denied (\"java.security.SecurityPermission\" \"getProperty.org.bouncycastle.rsa.max_size\")".

I took the archive here : 
https://github.com/aiven/encrypted-repository-opensearch/releases/tag/v2.9.0.0

Thanks

**Comment by willyborankin** [comment]
Fixed in this https://github.com/aiven/encrypted-repository-opensearch/pull/75. Most probably will prepare a new release later today

**Comment by pmarjou22** [comment]
Thanks, I built locally the plugin from the branch "fix permission check".

I remove / install the new built plugin on all my opensearch nodes and still get the problem

```
{
  "error": {
    "root_cause": [
      {
        "type": "execution_exception",
        "reason": "execution_exception: java.security.AccessControlException: access denied (\"java.security.SecurityPermission\" \"getProperty.org.bouncycastle.rsa.max_size\")"
      }
    ],
    "type": "repository_verification_exception",
    "reason": "[s3-repositoryencr] path [xxxxxxxxxxxxxxxxxxxxx/opensearchbackupencrypted] is not accessible on cluster-manager node",
    "caused_by": {
      "type": "repository_exception",
      "reason": "[s3-repositoryencr] cannot create blob store",
      "caused_by": {
        "type": "execution_exception",
        "reason": "execution_exception: java.security.AccessControlException: access denied (\"java.security.SecurityPermission\" \"getProperty.org.bouncycastle.rsa.max_size\")",
        "caused_by": {
          "type": "security_exception",
          "reason": "access denied (\"java.security.SecurityPermission\" \"getProperty.org.bouncycastle.rsa.max_size\")"
        }
      }
    }
  },
  "status": 500
}
```

**Comment by willyborankin** [comment]
Could you plz send me the full stack?

**Comment by pmarjou22** [comment]
`[2023-07-28T12:44:07,089][WARN ][r.suppressed             ] [ES_COORD_0] path: /_snapshot/s3-repositoryencr, params: {pretty=true, repository=s3-repositoryencr}
org.opensearch.transport.RemoteTransportException: [ES_MASTERHA_0][10.9.42.187:9300][cluster:admin/repository/put]
Caused by: org.opensearch.repositories.RepositoryVerificationException: [s3-repositoryencr] path [Analyticsxxxxxxxxxxxxxxxxxxxxxxxxxx/opensearchbackupencrypted] is not accessible on cluster-manager node
	at org.opensearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:1861) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.repositories.RepositoriesService$3.doRun(RepositoriesService.java:329) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.9.0.jar:2.9.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.opensearch.repositories.RepositoryException: [s3-repositoryencr] cannot create blob store
	at org.opensearch.repositories.blobstore.BlobStoreRepository.blobStore(BlobStoreRepository.java:752) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:1851) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.repositories.RepositoriesService$3.doRun(RepositoriesService.java:329) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.9.0.jar:2.9.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.opensearch.common.io.stream.NotSerializableExceptionWrapper: execution_exception: java.security.AccessControlException: access denied ("java.security.SecurityPermission" "getProperty.org.bouncycastle.rsa.max_size")
	at org.opensearch.common.cache.Cache.computeIfAbsent(Cache.java:464) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.repository.encrypted.EncryptedRepository.createBlobStore(EncryptedRepository.java:138) ~[?:?]
	at org.opensearch.repositories.blobstore.BlobStoreRepository.blobStore(BlobStoreRepository.java:748) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:1851) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.repositories.RepositoriesService$3.doRun(RepositoriesService.java:329) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.9.0.jar:2.9.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.SecurityException: access denied ("java.security.SecurityPermission" "getProperty.org.bouncycastle.rsa.max_size")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:485) ~[?:?]
	at java.security.AccessController.checkPermission(AccessController.java:1068) ~[?:?]
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:416) ~[?:?]
	at java.security.Security.getProperty(Security.java:742) ~[?:?]
	at org.bouncycastle.util.Properties$1.run(Unknown Source) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
	at org.bouncycastle.util.Properties.getPropertyValue(Unknown Source) ~[?:?]
	at org.bouncycastle.util.Properties.asInteger(Unknown Source) ~[?:?]
	at org.bouncycastle.crypto.params.RSAKeyParameters.validate(Unknown Source) ~[?:?]
	at org.bouncycastle.crypto.params.RSAKeyParameters.<init>(Unknown Source) ~[?:?]
	at org.bouncycastle.crypto.params.RSAPrivateCrtKeyParameters.<init>(Unknown Source) ~[?:?]
	at org.bouncycastle.crypto.params.RSAPrivateCrtKeyParameters.<init>(Unknown Source) ~[?:?]
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.RSAUtil.generatePrivateKeyParameter(Unknown Source) ~[?:?]
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.DigestSignatureSpi.engineInitSign(Unknown Source) ~[?:?]
	at java.security.Signature$Delegate.engineInitSign(Signature.java:1370) ~[?:?]
	at java.security.Signature.initSign(Signature.java:635) ~[?:?]
	at org.opensearch.repository.encrypted.security.EncryptionDataSerializer.sign(EncryptionDataSerializer.java:118) ~[?:?]
	at org.opensearch.repository.encrypted.security.EncryptionDataSerializer.lambda$serialize$0(EncryptionDataSerializer.java:55) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
	at org.opensearch.repository.encrypted.Permissions.doPrivileged(Permissions.java:21) ~[?:?]
	at org.opensearch.repository.encrypted.security.EncryptionDataSerializer.serialize(EncryptionDataSerializer.java:49) ~[?:?]
	at org.opensearch.repository.encrypted.EncryptedRepository.createOrRestoreEncryptionData(EncryptedRepository.java:178) ~[?:?]
	at org.opensearch.common.cache.Cache.computeIfAbsent(Cache.java:461) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.repository.encrypted.EncryptedRepository.createBlobStore(EncryptedRepository.java:138) ~[?:?]
	at org.opensearch.repositories.blobstore.BlobStoreRepository.blobStore(BlobStoreRepository.java:748) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:1851) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.repositories.RepositoriesService$3.doRun(RepositoriesService.java:329) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.9.0.jar:2.9.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by willyborankin** [comment]
Hmmm this is strange. Will take a look

**Comment by willyborankin** [comment]
I tested it with GCS the cloud repo is not so important. I couldn't reproduce the problem sorry.

**Comment by willyborankin** [comment]
You need private and public RSA keys not only private.

**Comment by willyborankin** [comment]
But the bug was in it and Im planning to release a new version in any case.

**Comment by pmarjou22** [comment]
> You need private and public RSA keys not only private.

Sorry I don't understand your reply, We do have public and private RSA keys in the opensearch keystore. The only change we made is a format change for PCK8 on the private key at first

![image](https://github.com/aiven/encrypted-repository-opensearch/assets/76211197/04078cde-13fd-49f6-a1cc-88754d8e6eba)

**Comment by willyborankin** [comment]
@pmarjou22 Sorry for the later response. If it is still relevant, I reproduced the issue, and it is related to the OS, not the plugin. It looks like the security plugin re-writes the encrypted plugin permissions since they both uses `BouncyCastle`. Again, I'm sorry that it took so much time to understand what's up. So far I do not know how to fix the problem and can recommend you do not use 2.9 until the problem will be fixed.

**Comment by willyborankin** [comment]
was fixed
